### ISSUE TITLE
Deploy Graph Nodes and 721 & 1155 Subgraphs

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/game-subgraphs#6]
Ensure that we have Graph Nodes and ERC721 + ERC1155 subgraphs available for the following chains:
- [ ] BSC Mainnet 
- [ ] Polygon Mainnet
- [ ] Ethereum Mainnet
- [ ] Chronos Mainnet

**Comment by giladkah** [comment]
Is this something that we want to do? 
Can we move it to block/backlog if not? Or kill it!
CC @Arshia001

**Comment by alexvotofuture** [comment]
Closing this, as it's no longer relevant to our approach.  We will try out achieving the same effect using 3rd party NFT indexing APIs.
