### ISSUE TITLE
Goerli Subgraph is no longer syncing

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/game-subgraphs#7]
https://thegraph.com/hosted-service/subgraph/ryry79261/goerli-erc721-erc1155 is no longer syncing.

Figure out why and resolve.

**Comment by RyRy79261** [comment]
# Issue

Likely an uncaught exception, The Graph has no error logging yet alone handling or introspection 
https://thegraph.com/docs/en/developing/creating-a-subgraph/#non-fatal-errors 

# Path forward

Identify the Tx at the last block that killed the graph, then [`graft`](https://thegraph.com/docs/en/developing/creating-a-subgraph/#grafting-onto-existing-subgraphs) on to the existing one

**Comment by RyRy79261** [comment]
# Self destruct

Found a very complex self destructed contract, could be that some state was recorded for it n failed to query afterwards
https://goerli.etherscan.io/tx/0x72959a3f12794e65ca222c99e6e993b4881bb2e61950eebd449e2158d697d49f

**Comment by RyRy79261** [comment]
# Complex mint TX
https://goerli.etherscan.io/tx/0x87175d00acd80dbf87f7a9ef7500bb85056e57abf608bcd9b3861c5566e943b6#eventlog

**Comment by RyRy79261** [comment]
Unhealthy block is: 7764083

**Comment by RyRy79261** [comment]
Deployed with a modified fork of OZ subgraphs 
https://thegraph.com/hosted-service/subgraph/ryry79261/goerli-erc721-erc1155?version=pending

1155 batch transfer apparently was the issue, index out of bounds

we're 0.6 % away from the crash block at time of writing
